#!/bin/zsh

DIR_LOC="$HOME/.local/bin"
[[ -d "${DIR_LOC}" && ":${PATH}:" != *":${DIR_LOC}:"* ]] && PATH="${DIR_LOC}:${PATH}"

DIR_LOC="$HOME/.local/share/cargo/bin"
[[ -d "${DIR_LOC}" && ":${PATH}:" != *":${DIR_LOC}:"* ]] && PATH="${DIR_LOC}:${PATH}"

DIR_LOC="$HOME/.local/opt/mongo-tools/bin"
[[ -d "${DIR_LOC}" && ":${PATH}:" != *":${DIR_LOC}:"* ]] && PATH="${DIR_LOC}:${PATH}"


export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# Home dir cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"


export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.sock"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export LESSHISTFILE="-"
export PYTHONSTARTUP="${XDG_CONFIG_HOME:-$HOME/.config}/python/pythonrc"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"


: <<"END"
export LESS="-F -X $LESS"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
END

export MOZ_USE_XINPUT2="1"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
