#add_newline = true
command_timeout=1000

#[line_break]
#disabled = true

#[character]
#disabled = true
#style = "bg:#192330 fg:#cdcecf"
#success_symbol = ""
#error_symbol = ""
#vicmd_symbol = ""
#use_symbol_for_status = true

[directory]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[$read_only ]($style)[$path ]($style)[](fg:#cdcecf)"
read_only=" "
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[hostname]
disabled = true
style = "bg:#192330 fg:#cdcecf"
ssh_only = false
trim_at = ".local"

[username]
disabled = true
style_user = "bg:#192330 fg:#cdcecf"
style_root = "bg:#192330 fg:#cdcecf"
format = "[ $user]($style)"
show_always = true

[cmd_duration]
disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf)[ ]($style)[$duration]($style)[](fg:#cdcecf)"
show_notifications = true
min_time_to_notify = "9999"

[time]
disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf)[ ]($style)[$time]($style)[](fg:#cdcecf)"
time_format = "%T"
utc_time_offset = "1"
time_range = "00:00:00-06:00:00"

[memory_usage]
disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf)[$symbol]($style)[${ram}( | ${swap}) ]($style)[](fg:#cdcecf)"
symbol = "  "
threshold = 0


[git_branch]
#disabled = true
symbol = ""
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf) [$symbol $branch]($style) [](fg:#cdcecf)"
#format = "[$symbol$branch]($style)[](fg:#cdcecf)"

[git_commit]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf)[ ﰖ $hash]($style)[](fg:$style) "

[git_state]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "[](fg:#cdcecf)[State:($state( $progress_current/$progress_total))]($style)[](fg:$style) "
am = "APPLYING-MAILBOX"
am_or_rebase = "APPLYING-MAILBOX/REBASE"

[git_status]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
conflicted = "[](fg:#cdcecf) [Conflicted:${count}](bg:#192330) [](fg:#cdcecf)"
staged = "[](fg:#cdcecf) [Staged:${count}](bg:#192330) [](fg:#cdcecf)"
modified = "[](fg:#cdcecf) [Modified:${count}](bg:#192330) [](fg:#cdcecf)"
renamed = "[](fg:#cdcecf) [Renamed:${count}](bg:#192330) [](fg:#cdcecf)"
deleted = "[](fg:#cdcecf) [Deleted:${count}](bg:#192330) [](fg:#cdcecf)"
untracked = "[](fg:#cdcecf) [Untracked:${count}](bg:#192330) [](fg:#cdcecf)"
stashed = "[](fg:#cdcecf) [Stashed:${count}](bg:#192330) [](fg:#cdcecf)"
ahead = "[](fg:#cdcecf) [Ahead:${count} ](bg:#192330) [](fg:#cdcecf)"
behind = "[](fg:#cdcecf) [Behind:${count}](bg:#192330) [](fg:#cdcecf)"
diverged = "[](fg:#cdcecf) [Diverged:${count}נּ](bg:#192330)[ Ahead:${ahead_count} ][ Behind:${behind_count}][](fg:#cdcecf)"

[aws]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[conda]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[dart]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[elixir]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[elm]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[golang]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[java]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[nix_shell]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[nodejs]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)[](fg:#cdcecf)[$symbol$version]($style)[](fg:#cdcecf)"
symbol = " "

[package]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)[](fg:#cdcecf)[$symbol$version]($style)[](fg:#cdcecf)"

[php]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[python]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)[](fg:#cdcecf)[${symbol}${pyenv_prefix}${version}($virtualenv)]($style)[](fg:#cdcecf)"
symbol = " "

[lua]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)[](fg:#cdcecf)[${symbol}${version}]($style)[](fg:#cdcecf)"
symbol = " "

[ruby]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = " "

[rust]
#disabled = true
style = "bg:#192330 fg:#cdcecf"
format = "($style)"
symbol = "  "
